[book]
title = "RISC-V ALE Exercise Book v1.0.2"
authors = ["João Seródio", "Edson Borin"]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/discovery-unicamp/ale-exercise-book"
